document.write("<p>Curso: ")
document.write(asignatura.curso)
document.write("</p>")
document.write("<p>Estudiante: ")
document.write(asignatura.nombreEstudiante)
document.write("</p>")
document.write("<p>Email: ")
document.write(asignatura.email)
document.write("</p>")
